version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb_data_1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  backend:
    image: node_image_1
    container_name: node_container
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://mongodb:27017/user"
volumes:
  mongodb_data:
